---
title: "AirBnb PCA Example."
author: "Süheyla Şeker"
date: "04/09/2020"
output: 
  html_document:
    theme: journal 
  
---
# AirBnb PCA Analysis
In this notebook author used **PCA** and **T-SNE** techniques but I will focus on PCA in this exercise. First, author loads data and then reviews the structure of dataframe.The NaN values in the **last_review** and **reviews_per_month** columns occurs because of no reviews given in the first place. For **reviews_per_month**, he fills those values with 0's.Then, using **PCA** functions, the author tries to show multidimensional data with smaller number of variables by capturing the basic properties in the data, and calculates how much of the variance in the data can be explained by the number of components selected from the data. By drawing the results of the **PCA** into a plot, he visualizes how much the components explain the variance in the data. Finally, the author completes his analysis by drawing the covariance matrix between components.

# Reference
[Data visualization with T-SNE, PCA](https://www.kaggle.com/jrw2200/unsupervised-techniques-t-sne-pca-k-means)